"""crew#508: the research capability is graded from its own ledger, in both directions.

Founder, 2026-08-27: "everything needs to be feeding the machine to have real intelligence,
how is our general purpose research capability" and "we have to be inwardly facing as well as
outwardly facing, this needs to be demonstrated in the showcase".

The defect this test exists to prevent: a page that prints a research capability as healthy
while a question sat 30 days with no decision, or that prints a foresight hit rate with no
model behind it. A stale question is a RED row on the page or this test fails.
"""
from __future__ import annotations

import datetime as dt
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "science"))

import research_grade as rg

TODAY = dt.date(2026, 8, 27)

LEDGER_ROWS = [
    # fed a decision the day it was asked, 3 sources
    {"date": "2026-08-26", "question": "Which catalogue does the estate run on?",
     "decision_fed": "Backstage for the catalogue, SQLite behind it.",
     "sources": ["https://backstage.io/docs", "https://a2a-protocol.org/", "https://opentofu.org/"],
     "findings": ["hosted portals price per seat"], "owner": "platform"},
    # open, 2 days old -> not stale
    {"date": "2026-08-25", "question": "What grades an identity population?",
     "decision_fed": None, "sources": ["https://www.w3.org/TR/webauthn-2/"],
     "findings": [], "owner": "platform", "ticket": "crew#227"},
    # open, 30 days old -> RED
    {"date": "2026-07-28", "question": "What should replace the launchd scheduler?",
     "decision_fed": "", "sources": [], "findings": [], "owner": "operations",
     "ticket": "crew#247"},
]


def _ledger(tmp_path: pathlib.Path) -> pathlib.Path:
    p = tmp_path / "RESEARCH-LEDGER.jsonl"
    p.write_text("".join(json.dumps(r) + "\n" for r in LEDGER_ROWS))
    return p


def test_counts_are_read_from_the_ledger(tmp_path):
    g = rg.grade(rg.read_ledger(_ledger(tmp_path)), TODAY)
    assert g["questions"] == 3
    assert g["decisions_fed"] == 1          # None and "" are not decisions
    assert g["open"] == 2
    assert g["fed_pct"] == 33
    assert g["sources_total"] == 4
    assert g["sources_median"] == 1.0
    assert g["sourceless"] == 1
    assert g["median_hours_to_decision"] == 0.0   # day-granular rows are a floor, not a guess
    assert g["day_only_rows"] == 1


def test_a_question_over_seven_days_without_a_decision_is_a_red_row(tmp_path):
    ledger = _ledger(tmp_path)
    g = rg.grade(rg.read_ledger(ledger), TODAY)
    assert len(g["stale"]) == 1, "only the 30-day question is stale"
    stale = g["stale"][0]
    assert stale["age_days"] == 30
    assert stale["ticket"] == "crew#247"
    page = rg.render(g, ledger, TODAY)
    assert "| RED 30d |" in page, "the stale question must render as a RED row"
    assert "crew#247" in page
    assert "What should replace the launchd scheduler?" in page


def test_page_is_two_graded_blocks_and_names_no_absolute_path(tmp_path):
    ledger = _ledger(tmp_path)
    page = rg.render(rg.grade(rg.read_ledger(ledger), TODAY), ledger, TODAY)
    assert "## Outward" in page and "## Inward" in page
    assert any(f"| Outward | **{v}**" in page for v in ("ELITE", "GAP", "BLIND"))
    assert any(f"| Inward | **{v}**" in page for v in ("ELITE", "GAP", "BLIND"))
    assert "/Users/" not in page and "/private/tmp/" not in page


def test_committed_page_carries_no_absolute_path():
    page = rg.PAGE
    if not page.exists():
        return  # generated by `python3 science/research_grade.py`; nothing to check yet
    text = page.read_text()
    assert "/Users/" not in text and "/private/tmp/" not in text


def test_check_exits_one_when_a_question_is_stale(tmp_path):
    ledger = _ledger(tmp_path)
    out = tmp_path / "RESEARCH-GRADE.md"
    # --today pins the clock: the fixture dates are fixed, and at 2026-08-28T00:00Z the row
    # aged to 31d and every PR went red (crew#547 qa 33129059210).
    assert rg.main(["--ledger", str(ledger), "--out", str(out), "--check", "--today", TODAY.isoformat()]) == 1
    assert "RED 30d" in out.read_text()


def test_grades_call_a_blind_block_blind():
    blind = rg.grades({"questions": 0, "stale": [], "sourceless": 0},
                      {"trained": False, "evidence": "-", "scored": 0})
    assert blind == ("BLIND", "BLIND")
    elite = rg.grades({"questions": 5, "stale": [], "sourceless": 0},
                      {"trained": True, "evidence": "science/foresight-state.json", "scored": 4})
    assert elite == ("ELITE", "ELITE")
