"""The evidence check read a marker in the body and ignored the file in the commit.

INCIDENT, 2026-08-24. `pr-evidence.py check` opened with `if MARKER not in body` and
returned "has no verification evidence". The marker is an HTML comment written into the
pull request body by `attach`. A body is prose: `gh pr edit --body-file` replaces it
whole and takes the marker with it, which is the ordinary way a body gets rewritten.

Measured that day on crew: #156 and #159 were red for it, and #137 was red for it while
`docs/evidence/pr-137/20260824T080641Z-1.png` sat committed in #137's own diff. The
images were never in doubt. Only the sentence pointing at them had been overwritten.

The class is grading a proxy: a marker in editable prose is a CLAIM that evidence exists,
and the file the diff adds IS the evidence. These tests assert that rule, not the code
that implements it. They test `evidence_paths`, which is the seam, so they need no network
and no `gh`.

SECOND INCIDENT, same day, in the first attempt at this fix. The replacement read the diff
for `^\\+\\+\\+ b/<path>` and found nothing, because **git prints no `---`/`+++` lines for a
binary file** -- and evidence is screenshots. The fixtures below were fabricated from memory
in that shape, so they agreed with the broken regex and five tests passed against a fix that
did not work on #137's real diff. Every fixture here is now a transcript of real `git show`
output: the add and delete shapes were generated by committing and removing a real PNG, and
the delete shape was confirmed a second time against crew commit 5ff4d44, which removed
`docs/evidence/the-review-gate-read-a-whole-line-as-a-name.png`. That is the reason a fixture
in this file is never hand-written.

Rung 4, incident tests, one per bug, named for the bug.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "pr-evidence.py"

MARKER = "<!-- pr-evidence -->"

#: Verbatim `git show` output for an added PNG. Note what is NOT here: no `---`, no `+++`,
#: no hunk. The `diff --git` header is the only line carrying the path.
DIFF_ADDS_IMAGE = (
    "diff --git a/docs/evidence/pr-137/20260824T080641Z-1.png "
    "b/docs/evidence/pr-137/20260824T080641Z-1.png\n"
    "new file mode 100644\n"
    "index 0000000..31cabef\n"
    "Binary files /dev/null and b/docs/evidence/pr-137/20260824T080641Z-1.png differ\n"
)

#: Verbatim `git show` output for a REMOVED PNG. The header is identical to an add -- git
#: names the path on both sides either way -- so the only thing separating them is the
#: `deleted file mode` line and which side of `Binary files ... differ` is /dev/null.
DIFF_DELETES_IMAGE = (
    "diff --git a/docs/evidence/pr-120/20260824T071911Z-1.png "
    "b/docs/evidence/pr-120/20260824T071911Z-1.png\n"
    "deleted file mode 100644\n"
    "index 31cabef..0000000\n"
    "Binary files a/docs/evidence/pr-120/20260824T071911Z-1.png and /dev/null differ\n"
)

#: An ADD of an image belonging to a different pull request -- what #137 does when it puts back
#: the screenshots deleted from #120 and #128. Written out in full rather than derived from
#: DIFF_DELETES_IMAGE by string surgery: swapping `deleted file mode` for `new file mode` leaves
#: the `Binary files a/... and /dev/null differ` line behind, which still reads as a deletion.
#: That mistake made this very test pass for the wrong reason on its first run.
DIFF_RESTORES_OTHER_IMAGE = (
    "diff --git a/docs/evidence/pr-120/20260824T071911Z-1.png "
    "b/docs/evidence/pr-120/20260824T071911Z-1.png\n"
    "new file mode 100644\n"
    "index 0000000..31cabef\n"
    "Binary files /dev/null and b/docs/evidence/pr-120/20260824T071911Z-1.png differ\n"
)

#: A docs-only pull request's evidence: pasted command output, no screenshot. This is #139's
#: real shape, trimmed. The old marker gate passed it because the comment was present; it
#: would equally have passed an entirely empty section.
BODY_WITH_TRANSCRIPT = (
    f"{MARKER}\n## Verification evidence\n\n"
    "Ledger schema validated against the existing rows before appending.\n\n"
    "```\n$ git status --porcelain\nM  science/RESEARCH-LEDGER.jsonl\n"
    "A  science/control-plane-replacement.md\n```\n\n"
    f"<!-- /pr-evidence -->\n\n## Options considered\n\n- **Chosen:** ship it\n"
)

#: The same section with nothing in it. The marker is present, so the old gate passed this.
BODY_WITH_EMPTY_SECTION = (
    f"{MARKER}\n## Verification evidence\n\n"
    f"<!-- /pr-evidence -->\n\n## Options considered\n\n- **Chosen:** ship it\n"
)

#: A text file that merely TALKS about an evidence path. This is the shape that would fool
#: any pattern searching the diff body rather than the file headers.
DIFF_MENTIONS_PATH_IN_TEXT = (
    "diff --git a/README.md b/README.md\n"
    "index 1111111..2222222 100644\n"
    "--- a/README.md\n"
    "+++ b/README.md\n"
    "@@ -1,2 +1,3 @@\n"
    " # crew\n"
    "+See docs/evidence/pr-137/20260824T080641Z-1.png for the run.\n"
)

BODY_WITH_LINK = (
    f"{MARKER}\n## Verification evidence\n\n"
    "![shot](https://github.com/chidionyema/crew/blob/some-branch"
    "/docs/evidence/pr-137/20260824T080641Z-1.png?raw=1)\n"
)

BODY_REPLACED_BY_HAND = (
    "fix(pr-evidence): commit the files it was handed\n\n"
    "Author-session: ffe3de4d\nReviewed-by: chidionyema-73\n\n"
    "Rewritten from a file, so nothing of the generated section survives.\n"
)


def _mod():
    spec = importlib.util.spec_from_file_location("pr_evidence", SCRIPT)
    assert spec is not None and spec.loader is not None, f"cannot load {SCRIPT}"
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_incident_a_body_rewritten_without_the_marker_still_has_its_committed_evidence():
    """The incident. No marker, no link, and the image is right there in the diff."""
    paths, where = _mod().evidence_paths(BODY_REPLACED_BY_HAND, DIFF_ADDS_IMAGE)
    assert paths == {"docs/evidence/pr-137/20260824T080641Z-1.png"}, (
        "a body edit must not be able to delete evidence that is committed"
    )
    assert where == "committed in the diff"


def test_incident_a_binary_file_has_no_plus_plus_plus_line():
    """The second incident, asserted directly rather than as a side effect.

    The first fix searched for `+++ b/<path>`. If a future change reaches for that pattern
    again this test says why it cannot work, in the fixture itself.
    """
    assert "+++" not in DIFF_ADDS_IMAGE
    assert "--- " not in DIFF_ADDS_IMAGE
    paths, _ = _mod().evidence_paths(BODY_REPLACED_BY_HAND, DIFF_ADDS_IMAGE)
    assert paths, "the rule must read the `diff --git` header, not a hunk that never exists"


def test_a_pull_request_that_only_links_evidence_is_still_read_the_old_way():
    """The permit direction. LAW 38: the fix must not refuse work the old check allowed.

    An empty diff is the case where nothing was committed on this branch. The body's link
    is all there is, and it still counts, exactly as it did before.
    """
    paths, where = _mod().evidence_paths(BODY_WITH_LINK, "")
    assert paths == {"/docs/evidence/pr-137/20260824T080641Z-1.png"}
    assert where == "linked from the body"


def test_a_pull_request_with_neither_is_still_refused():
    """The refuse direction. Removing the marker gate must not remove the floor."""
    paths, _ = _mod().evidence_paths(
        BODY_REPLACED_BY_HAND, "diff --git a/README.md b/README.md\n")
    assert paths == set()


def test_deleting_an_evidence_image_does_not_count_as_attaching_one():
    """A diff that only REMOVES evidence has not evidenced anything.

    The trap in reading a diff for paths: a deletion's `diff --git` header names the path on
    both sides, exactly like an add. Match the header alone and a pull request satisfies the
    gate by deleting somebody else's screenshot.
    """
    paths, _ = _mod().evidence_paths(BODY_REPLACED_BY_HAND, DIFF_DELETES_IMAGE)
    assert paths == set()


def test_a_pull_request_that_adds_and_deletes_counts_only_what_it_added():
    """#137's real shape: it restores two images and adds its own.

    This is the test the per-section reading exists for. A pattern applied to the whole diff
    cannot tell which section a `deleted file mode` line belongs to, so it either counts the
    deletion or discards the add.
    """
    paths, where = _mod().evidence_paths(
        BODY_REPLACED_BY_HAND, DIFF_DELETES_IMAGE + DIFF_ADDS_IMAGE)
    assert paths == {"docs/evidence/pr-137/20260824T080641Z-1.png"}
    assert where == "committed in the diff"


def test_restoring_another_pull_requests_evidence_is_not_evidence_for_this_one():
    """The mirror of the deletion trap, found by running the fix against #137's real diff.

    #137 restores two screenshots that were deleted from #120 and #128 and adds one of its
    own. Unscoped, the restorations read as #137's verification -- so a pull request could
    satisfy the gate by restoring somebody else's evidence and attaching none.

    Scoped to #120, the restoration is exactly what it is: evidence for #120.
    """
    mod = _mod()
    diff = DIFF_RESTORES_OTHER_IMAGE + DIFF_ADDS_IMAGE
    for_137, _ = mod.evidence_paths(BODY_REPLACED_BY_HAND, diff, 137)
    assert for_137 == {"docs/evidence/pr-137/20260824T080641Z-1.png"}
    for_120, _ = mod.evidence_paths(BODY_REPLACED_BY_HAND, diff, 120)
    assert for_120 == {"docs/evidence/pr-120/20260824T071911Z-1.png"}
    unscoped, _ = mod.evidence_paths(BODY_REPLACED_BY_HAND, diff)
    assert len(unscoped) == 2, "unscoped stays the old, wider reading"


def test_a_docs_only_pull_request_evidences_itself_with_a_command_transcript():
    """LAW 38, found by running the new rule against all ten open pull requests.

    #139 changes two text files. It has no screenshot and cannot usefully have one, and its
    evidence is pasted `git status` and secret-scan output. An images-only rule flipped it
    from green to red -- correct work refused, which is the outage the fix was supposed to
    prevent, reintroduced from the other side.
    """
    assert _mod().transcript_evidence(BODY_WITH_TRANSCRIPT) == 1


def test_an_empty_evidence_section_is_still_refused():
    """And the floor. The marker gate accepted a heading with nothing under it.

    This is the difference between grading the proxy and grading the artifact: the section's
    presence proves nothing, the transcript inside it is the evidence.
    """
    assert _mod().transcript_evidence(BODY_WITH_EMPTY_SECTION) == 0
    assert _mod().transcript_evidence(BODY_REPLACED_BY_HAND) == 0


def test_talking_about_an_evidence_path_in_a_text_file_is_not_evidence():
    """Naming a screenshot is a claim; committing one is the evidence.

    Without this, editing a README to mention a path would satisfy the gate -- the same
    grade-a-proxy defect the whole fix exists to remove, reintroduced from the other side.
    """
    paths, _ = _mod().evidence_paths(BODY_REPLACED_BY_HAND, DIFF_MENTIONS_PATH_IN_TEXT)
    assert paths == set()
