"""crew#628 CP1, founder 2026-08-29: "NO ONE IS PROVING OR VERIFYING ANYTHING".

Until 2026-08-30 `pr-evidence.py check` counted every fence under `## Verification evidence` as
evidence, so a transcript the author typed passed the same as one the pipeline wrote. Measured
that morning: idp#802 carried one typed transcript beside the block bin/idp-verify-claims wrote.

Both ways, on literal bodies with the network stubbed:
  * a repository that runs the generator refuses a typed transcript and names the fix;
  * the generated block must name a run that exists;
  * a repository without the generator (crew#708 that day) still counts typed transcripts, with
    a plain note in the pass line, because refusing it would be a guard refusing correct work.
"""

from __future__ import annotations

import importlib.util
import pathlib

HERE = pathlib.Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("pr_evidence", HERE / "scripts" / "pr-evidence.py")
assert spec is not None and spec.loader is not None
pe = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pe)

FENCE = "```\n" + ("x" * (pe.TRANSCRIPT_MIN_CHARS + 5)) + "\n```\n"
GENERATED = (
    pe.GEN_START + "\n## Verification evidence (generated)\nGenerated by bin/idp-verify-claims"
    " in https://github.com/o/r/actions/runs/123\n" + FENCE + pe.GEN_END + "\n"
)
TYPED = "## Verification evidence\n\n" + FENCE
REST = (
    "## Options considered\n"
    "- Option one is a real option that was weighed and then rejected for a reason.\n"
    "- Option two is a real option that was weighed and then rejected for a reason.\n"
    "- Chosen: the road taken, and why it beat the two above in one sentence.\n\n"
    "Accept when: the check prints the expected verdict.\n\n"
    "## Definition of done\n"
    + "".join(f"{i}. {name} — n/a: test body\n" for i, name in enumerate(pe.DOD_ROWS, 1))
    + "\n## Architecture laws\n"
    "- LAW 1 zero-gravity: n/a: test body\n- LAW 2 fractal: n/a: test body\n"
    "- LAW 3 nervous system: n/a: test body\n- LAW 4 calibration: n/a: test body\n"
)


def _stub(monkeypatch, body: str, generator: bool, run_ok: bool = True):
    monkeypatch.setattr(
        pe,
        "pr_info",
        lambda pr, repo: {"number": 1, "body": body, "url": "https://github.com/o/r/pull/1"},
    )

    def gh(args, stdin=None):
        if args[:2] == ["pr", "diff"]:
            return "diff --git a/x b/x\n"
        if args[:2] == ["api", "repos/o/r/contents/.github/workflows/verify-claims.yml"] or (
            args[0] == "api" and "verify-claims.yml" in args[1]
        ):
            if generator:
                return ".github/workflows/verify-claims.yml\n"
            raise pe.Fail("404")
        if args[:2] == ["run", "view"]:
            if run_ok:
                return f'{{"databaseId": {args[2]}}}'
            raise pe.Fail("no run")
        raise AssertionError(f"unexpected gh call {args}")

    monkeypatch.setattr(pe, "gh", gh)


def test_generated_and_typed_are_told_apart_on_literal_bodies():
    assert pe.generated_evidence("Verify: `true`\n" + GENERATED) == ("123", 0)
    assert pe.generated_evidence(TYPED + GENERATED) == ("123", 1)
    assert pe.generated_evidence(TYPED) == (None, 1)
    assert pe.generated_evidence("prose") == (None, 0)


def test_where_the_generator_runs_a_typed_transcript_is_refused_and_names_the_fix(monkeypatch):
    _stub(monkeypatch, TYPED + GENERATED + REST, generator=True)
    ok, why = pe.check("1", "o/r")
    assert not ok and "hand-typed" in why and "Verify:" in why


def test_where_the_generator_runs_the_block_passes_only_if_its_run_exists(monkeypatch):
    _stub(monkeypatch, "Verify: `true`\n" + GENERATED + REST, generator=True)
    ok, why = pe.check("1", "o/r")
    assert ok and "generated evidence block from run 123" in why
    _stub(monkeypatch, "Verify: `true`\n" + GENERATED + REST, generator=True, run_ok=False)
    ok, why = pe.check("1", "o/r")
    assert not ok and "names run 123" in why


def test_without_the_generator_a_typed_transcript_still_counts_and_the_pass_line_says_so(
    monkeypatch,
):
    _stub(monkeypatch, TYPED + REST, generator=False)
    ok, why = pe.check("1", "o/r")
    assert ok and "no verify-claims generator" in why
