"""crew#527 CP2: science/BOARD.md is the printed rank, regenerated by the velocity row from the one
picker; a missing or failing picker writes BLIND, never a stale page that reads as current."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "science"))
import velocity


def _picker(tmp_path: Path, body: str) -> Path:
    p = tmp_path / "estate_board.py"
    p.write_text(body)
    return p


def test_board_md_carries_the_picker_rank(tmp_path: Path) -> None:
    picker = _picker(tmp_path, 'import sys\nassert sys.argv[1:] == ["rank", "--top", "60"], sys.argv\n'
                               'print("finish-first rank, 2 unclaimed of 3 open (t)\\n  #227  4/6 lane:platform Auth v2")\n')
    out = tmp_path / "BOARD.md"
    assert velocity.write_board(out, picker, "2026-08-27T18:00:00Z") is True
    text = out.read_text()
    assert "# Board rank, finish-first" in text
    assert "#227  4/6" in text
    assert "BLIND" not in text


def test_missing_or_failing_picker_writes_blind(tmp_path: Path) -> None:
    out = tmp_path / "BOARD.md"
    out.write_text("stale rank #999")
    assert velocity.write_board(out, tmp_path / "nope.py", "t") is False
    assert "BLIND" in out.read_text() and "#999" not in out.read_text()
    failing = _picker(tmp_path, 'import sys\nprint("BLIND: the board cannot be read"); sys.exit(2)\n')
    assert velocity.write_board(out, failing, "t") is False
    assert "BLIND" in out.read_text() and "exit 2" in out.read_text()
