"""crew#495 CP2 (2026-08-27): the risk register listed 13 hazards while 10 open P1 issues
named none of them, so nobody could say which hazard a fire had realised or which fire had no
hazard behind it. Rule: the hazard page is generated from the register and the open P1s, and
--check refuses when an open P1 names no register row. Rung 4, both ways."""
import json
import os
import subprocess
import sys
from pathlib import Path

CREW = Path(__file__).resolve().parents[1]
GEN = CREW / "scripts" / "hazard-register"


def _run(tmp: Path, issues: list[dict]) -> tuple[int, str, str]:
    f = tmp / "issues.json"
    f.write_text(json.dumps(issues))
    out = tmp / "HAZARDS.md"
    r = subprocess.run([sys.executable, str(GEN), "--check", "--issues", str(f), "--out", str(out)],
                       capture_output=True, text=True, check=False, env={**os.environ, "CREW_ROOT": str(CREW)})
    return r.returncode, r.stdout, out.read_text()


def test_a_p1_that_names_no_hazard_is_a_finding_and_one_that_does_is_linked(tmp_path: Path) -> None:
    named = {"repo": "chidionyema/crew", "number": 1, "title": "fire", "body": "realises R1 twice", "url": "u1"}
    unnamed = {"repo": "chidionyema/idp", "number": 2, "title": "orphan fire", "body": "no id here", "url": "u2"}
    rc, out, page = _run(tmp_path, [named, unnamed])
    assert rc == 1 and "1 name no hazard" in out and "chidionyema/idp#2" in out
    assert "[crew#1](u1)" in page and "- [idp#2](u2) orphan fire" in page
    rc, out, page = _run(tmp_path, [named])
    assert rc == 0 and "0 name no hazard" in out and "- none" in page


def test_open_hazards_come_first_and_the_page_is_generated(tmp_path: Path) -> None:
    _, _, page = _run(tmp_path, [])
    statuses = [line.split("|")[2].strip() for line in page.splitlines() if line.startswith("| R")]
    assert statuses and statuses == sorted(statuses, key=lambda s: s != "open")
    assert "GENERATED by `scripts/hazard-register`" in page
